import { config } from "dotenv";

config({ path: `.env.${process.env.NODE_ENV || "development"}` });

export const {
    PORT, NODE_ENV, SERVER_URL,
    SERVER_PROD_URL, RESERVE_PORT,
    JWT_SECRET, JWT_EXPIRATION, TOKEN_ID, TOKEN_PRE_FIX,
    IP_ALLOWED_ADDRESSES, STATIC_OUTBOUND_IP_ADDRESSES,
    ATLAS_DB_NAME,ATLAS_DB_COLLECTION, ATLAS_URI,
    DEFAULT_USER_AVATAR,
    FIREBASE_URL, GOOGLE_API, CLOUDINARY_URL,
    CORP_EMAIL_ADDRESS, HOST_SERVICE, HOST_PORT,
    EMAIL_ADDRESS, EMAIL_PASSWORD,
    CLIENT_PORT, CLIENT_URL,
} = process.env;