export const ExpenseCategoryOptions = {
  RENT: 'RENT',
  GROCERIES: 'GROCERIES',
  UTILITIES: 'UTILITIES',
  TRANSPORTATION: 'TRANSPORTATION',
  INSURANCE: 'INSURANCE',
  HEALTHCARE: 'HEALTHCARE',
  DEBT: 'DEBT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  DINING_OUT: 'DINING_OUT',
  EDUCATION: 'EDUCATION',
  PERSONAL_CARE: 'PERSONAL_CARE',
  SAVINGS: 'SAVINGS',
  INVESTMENTS: 'INVESTMENTS',
  GIFTS: 'GIFTS',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  CHILDCARE: 'CHILDCARE',
  TRAVEL: 'TRAVEL',
  TAXES: 'TAXES',
  OTHER: 'OTHER',
} as const;

export type ExpenseCategoryTypes = keyof typeof ExpenseCategoryOptions;

export const IncomeSourceOptions = {
  SALARY: 'SALARY',
  FREELANCE: 'FREELANCE',
  BUSINESS: 'BUSINESS',
  INVESTMENTS: 'INVESTMENTS',
  RENTAL_INCOME: 'RENTAL_INCOME',
  INTEREST: 'INTEREST',
  DIVIDENDS: 'DIVIDENDS',
  GIFTS: 'GIFTS',
  REFUNDS: 'REFUNDS',
  BONUS: 'BONUS',
  GRANTS: 'GRANTS',
  PENSION: 'PENSION',
  CRYPTO: 'CRYPTO',
  OTHER: 'OTHER',
} as const;

export type IncomeSourceTypes = keyof typeof IncomeSourceOptions;